#Generated by Fabric Compiler ( version 2025.2 <build 211867> ) at Thu Sep 17 21:54:58 2026

add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/alu.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/csr_file.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ctrl.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/decoder.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ex.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/fetch.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/forward.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/lmb.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pc_reg.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pipeline.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/reg_file.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/wb.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/bus.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ddr_interface.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/flash.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/io.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ram.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/reset_sync.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_rx.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_tx.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/soc.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_control.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_csr.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_dhazards.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_interrupt.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_pipeline.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/AbortDelay.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/BlockQ.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/blocktim.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest2.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest_strings.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/countsem.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crflash.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crhook.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/death.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/dynamic.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/EventGroupsDemo.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/fileIO.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash_timer.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flop.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/GenQTest.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/integer.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntQueue.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntSemTest.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferAMP.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferDemo.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/mevents.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/partest.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/PollQ.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/print.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QPeek.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueOverwrite.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSet.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSetPolling.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/recmutex.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/semtest.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/serial.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StaticAllocation.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferDemo.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferInterrupt.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotify.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotifyArray.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TimerDemo.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/FreeRTOSConfig.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/ns16550.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-reg.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-virt.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/atomic.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/croutine.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/deprecated_definitions.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/event_groups.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/FreeRTOS.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/list.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/message_buffer.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_prototypes.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_syscall_numbers.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_wrappers.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/newlib-freertos.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/picolibc-freertos.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/portable.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/projdefs.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/queue.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/semphr.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stack_macros.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/StackMacros.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stream_buffer.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/task.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/timers.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/freertos_risc_v_chip_specific_extensions.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portContext.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portmacro.h"
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/mini_libc/include/mini_io.h"
remove_design -verilog "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv"
remove_design -verilog "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv"
remove_design -verilog "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv"
add_design D:/workspace/FPGA/RVCPU/ipcore/u_ddr/u_ddr.idf
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc} top_library {work}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
launch_tasks [get_tasks {syn_1}] -to_action synthesize
wait_on_tasks [get_tasks {syn_1}] -to_action synthesize
launch_tasks [get_tasks {pnr_1}] -to_action dev_map
wait_on_tasks [get_tasks {pnr_1}] -to_action dev_map
launch_tasks [get_tasks {pnr_1}] -to_action dev_map
wait_on_tasks [get_tasks {pnr_1}] -to_action dev_map
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc} top_library {work}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/alu.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/csr_file.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ctrl.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/decoder.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ex.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/fetch.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/forward.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/lmb.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pc_reg.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pipeline.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/reg_file.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/wb.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/bus.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ddr_interface.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/flash.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/io.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ram.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/reset_sync.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_rx.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_tx.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/soc.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_control.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_csr.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_dhazards.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_interrupt.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_pipeline.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/AbortDelay.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/BlockQ.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/blocktim.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest2.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest_strings.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/countsem.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crflash.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crhook.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/death.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/dynamic.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/EventGroupsDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/fileIO.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash_timer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flop.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/GenQTest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/integer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntQueue.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntSemTest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferAMP.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/mevents.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/partest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/PollQ.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/print.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QPeek.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueOverwrite.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSet.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSetPolling.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/recmutex.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/semtest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/serial.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StaticAllocation.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferInterrupt.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotify.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotifyArray.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TimerDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/FreeRTOSConfig.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/ns16550.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-reg.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-virt.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/atomic.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/croutine.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/deprecated_definitions.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/event_groups.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/FreeRTOS.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/list.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/message_buffer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_prototypes.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_syscall_numbers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_wrappers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/newlib-freertos.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/picolibc-freertos.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/portable.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/projdefs.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/queue.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/semphr.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stack_macros.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/StackMacros.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stream_buffer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/task.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/timers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/freertos_risc_v_chip_specific_extensions.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portContext.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portmacro.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/mini_libc/include/mini_io.h" -library work -verilog
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv"
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv"
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv"
add_design "D:/workspace/FPGA/RVCPU/ipcore/u_ddr/u_ddr.idf"
set_option {max_threads} {0}
set_option -options {top_module	soc	top_library	work} [get_filesets design_1]
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/alu.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/csr_file.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ctrl.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/decoder.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ex.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/fetch.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/forward.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/lmb.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pc_reg.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pipeline.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/reg_file.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/wb.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/bus.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ddr_interface.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/flash.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/io.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ram.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/reset_sync.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_rx.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_tx.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/soc.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_control.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_csr.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_dhazards.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_interrupt.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_pipeline.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv" -library work
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/AbortDelay.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/BlockQ.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/blocktim.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest2.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/comtest_strings.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/countsem.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crflash.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/crhook.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/death.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/dynamic.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/EventGroupsDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/fileIO.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flash_timer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/flop.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/GenQTest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/integer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntQueue.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/IntSemTest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferAMP.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/MessageBufferDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/mevents.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/partest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/PollQ.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/print.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QPeek.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueOverwrite.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSet.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/QueueSetPolling.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/recmutex.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/semtest.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/serial.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StaticAllocation.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/StreamBufferInterrupt.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotify.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TaskNotifyArray.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Demo/Common/include/TimerDemo.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/FreeRTOSConfig.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/ns16550.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-reg.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/riscv-virt.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/atomic.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/croutine.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/deprecated_definitions.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/event_groups.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/FreeRTOS.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/list.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/message_buffer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_prototypes.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_syscall_numbers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/mpu_wrappers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/newlib-freertos.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/picolibc-freertos.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/portable.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/projdefs.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/queue.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/semphr.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stack_macros.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/StackMacros.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/stream_buffer.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/task.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/include/timers.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/freertos_risc_v_chip_specific_extensions.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portContext.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/FreeRTOS/Source/portable/RISC-V/portmacro.h" -library work -verilog
add_design "D:/workspace/FPGA/RVCPU/risc-mini/src/mini_libc/include/mini_io.h" -library work -verilog
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/cpu.sv"
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/data_path.sv"
remove_design "D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv"
add_design "D:/workspace/FPGA/RVCPU/ipcore/u_ddr/u_ddr.idf"
set_option {max_threads} {0}
set_option -options {top_module	soc	top_library	work} [get_filesets design_1]
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
set_option -options {top_module	soc	top_library	work} [get_filesets design_1]
set_option -options {top_module	soc	top_library	work} [get_filesets design_1]
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
set_option max_threads 0
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
set_option -options { top_module {soc}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
launch_tasks [get_tasks {syn_1}] -to_action synthesize
wait_on_tasks [get_tasks {syn_1}] -to_action synthesize
