# ----------------------------------------
# Created on: Fri Sep 18 20:57:08 2026
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlib  u_ddr
vmap  u_ddr ./u_ddr
vmap  usim "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/usim"
vmap  adc_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/adc_e2"
vmap  ddc_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ddc_e2"
vmap  dll_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/dll_e2"
vmap  hsstlp_lane "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/hsstlp_lane"
vmap  hsstlp_pll "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/hsstlp_pll"
vmap  iolhr_dft "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/iolhr_dft"
vmap  ipal_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ipal_e2"
vmap  ipal_e5 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ipal_e5"
vmap  iserdes_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/iserdes_e2"
vmap  oserdes_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/oserdes_e2"
vmap  mipi_dphy_tx_e1 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/mipi_dphy_tx_e1"
vmap  mipi_dphy_rx_e1 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/mipi_dphy_rx_e1"
vmap  ddrs "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ddrs"
vmap  ddrs_dft "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ddrs_dft"
vmap  sensor_e2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/sensor_e2"
vmap  pciegen2 "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/pciegen2"
vmap  ppm "D:/workspace/FPGA/RVCPU/pango_sim_libraries/modelsim/ppm"
vlog -work work  \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/soc.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/alu.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/csr_file.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ctrl.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/decoder.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/ex.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/fetch.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/forward.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/lmb.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pc_reg.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/pipeline.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/reg_file.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/core/wb.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/bus.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ddr_interface.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/flash.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/io.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/ram.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/reset_sync.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_rx.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/rtl/peripherals/uart_tx.sv" \
"D:/workspace/FPGA/RVCPU/risc-mini/sim/tb_soc.sv" 
vlog -work u_ddr  \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ips2l_rst_sync_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_wrlvl_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_wrcal_v1_7.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_wdata_path_adj_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_upcal_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_training_ctrl_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_slice_rddata_align_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_reset_ctrl_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_rdcal_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_main_ctrl_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_init_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_info_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_gatecal_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_gate_update_ctrl_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_eyecal_v1_5.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_drift_ctrl_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_dqsi_rdel_cal_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_dqs_rddata_align_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_dqs_gate_coarse_cal_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_dll_update_ctrl_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_dfi_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_gpll_phase_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_data_slice_wrlvl_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_data_slice_wrcal_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_data_slice_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_data_slice_dqs_gate_cal_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_cpd_ctrl_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_cpd_lock_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_control_path_adj_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_calib_top_v1_10.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_calib_mux_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_rst_debounce_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/ips2l_ddrphy_rst_clk_phase_adj_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/pll/ips2l_ddrphy_gpll_v1_3.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/pll/ips2l_ddrphy_ppll_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_apb_cross_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_calib_delay_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_cfg_apb_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcd_bm_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcd_rowaddr_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcd_sm_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcd_top_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcp_back_ctrl_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcp_buf_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcp_out_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dcp_top_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_dfi_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_lp_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_mrs_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_prefetch_fifo_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_rdatapath_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_reg_fifo2_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_ui_axi_v1_2a.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_wdatapath_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_wdp_align_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_wdp_dcp_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/ips2l_mcdq_wrapper_v1_2b.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_com_timing_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_tfaw_timing_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_tfaw_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_act2wr_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_act_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_pre_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_rd_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_ref_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_wr_pass_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/syn_mod/ips2l_mcdq_trc_timing_v1_2.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/distributed_fifo/ips2l_distributed_fifo_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_fifo_ctr_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_fifo_v1_0_distributed_fifo_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_sdpram_v1_0_distributed_fifo_v1_0.vp" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/u_ddr.v" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/u_ddr_ddrphy_top.v" \
"D:/workspace/FPGA/RVCPU/ipcore/u_ddr/rtl/ddrphy/u_ddr_slice_top_v1_10.v" 

# ----------------------------------------
