# ----------------------------------------
# Created on: Fri Sep 18 20:57:09 2026
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt -suppress 12110  -L work -L u_ddr  -L usim -L adc_e2 -L ddc_e2 -L dll_e2 -L hsstlp_lane -L hsstlp_pll -L iolhr_dft -L ipal_e2 -L ipal_e5 -L iserdes_e2 -L oserdes_e2 -L mipi_dphy_tx_e1 -L mipi_dphy_rx_e1 -L ddrs -L ddrs_dft -L sensor_e2 -L pciegen2 -L ppm work.tb_soc usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
